docker-build-master:
  # Official docker image.
  image: docker:latest
  stage: build
  services:
    - docker:dind
  before_script:
    - docker login lockwebsitereg.azurecr.io -u lockwebsitereg -p TTundFwjKqc0p5MlLG1nq2BeMY=aTu32
  script:
    - docker build -t thereisanevening .
    - docker tag thereisanevening  lockwebsitereg.azurecr.io/thereisanevening
    - docker push lockwebsitereg.azurecr.io/thereisanevening
  only:
    - master
