version: '3.7'

services:
  front-end:
    container_name: front-end
    build:
      context: frontend/our-app
      dockerfile: Dockerfile
    volumes:
      - '.:/frontend/our-app'
      - '/frontend/our-app/node_modules'
    ports:
      - 3001:3000
    stdin_open: true   